# Site settings
title: "echidna"
logo_url: "/assets/images/logo.png"
email: marco.lizza@gmail.com
description: / night-time gamedev and geek /
url: "https://echidna.io" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

author: # Author details
  name: Marco Lizza
  email: marco.lizza@gmail.com
  url: https://echidna.io
  copyright: "&copy; Copyright 2014-2017 by Marco Lizza"

# Profile links, leave blank to ignore
social: 
  github: MarcoLizza
  twitter: MarcoLizza
  facebook: marco.lizza
  itchio: MarcoLizza 
  gplus: +MarcoLizza
  linkedin: marco-lizza-46569a34  
  disqus: echidna-io

# Google Analytics key, leave blank to ignore
google:
  analytics_key: UA-86128117-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title/

include:
  - _pages

exclude: 
  - CNAME
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .sass-cache

sass:
  sass_dir: assets/css/_sass
  style: :compressed

gems:
  - jekyll-tidy

jekyll_tidy:
  compress_html: false
